name: Auto Commit

on:
  schedule:
    - cron: "0 */4 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          default_author: github_actions
          message: "Auto-commit: Update README.md"
